"""Synthetic-only schema/transfer rehearsal, not a production migration tool."""
import pathlib
import re
import sqlite3
import subprocess
import datetime
import shutil
import os

psql_binary = os.environ.get("IDENTITY_REHEARSAL_PSQL") or shutil.which("psql")
if os.environ.get("IDENTITY_REHEARSAL_ENABLED") != "1":
    raise SystemExit("Synthetic rehearsal disabled; set IDENTITY_REHEARSAL_ENABLED=1 for a disposable local cluster on port 55441.")
if not psql_binary:
    raise SystemExit("Set IDENTITY_REHEARSAL_PSQL to the psql executable.")

source = (pathlib.Path(__file__).resolve().parents[1] / "internal/database/database.go").read_text(encoding="utf-8")
schema = re.search(r"const migration = `(.*?)`", source, re.S).group(1)
db = sqlite3.connect(":memory:")
db.executescript(schema)
db.execute("ALTER TABLE badges ADD COLUMN activation_pending BOOLEAN NOT NULL DEFAULT 0")
db.execute("INSERT INTO users(id,username,display_name,pin_hash,oidc_subject) VALUES(41,'fixture','Synthetic User','synthetic-hash','stable-fixture-subject')")
db.execute("INSERT INTO badges(id,badge_code,user_id,token_hash,enabled,activation_pending) VALUES(73,'FIXTURE-73',41,'synthetic-token-hash',0,1)")
db.execute("INSERT INTO audit_log(id,event_type,username,success,timestamp,details) VALUES(19,'fixture_event','fixture',1,'2026-01-02 03:04:05','synthetic audit')")
db.execute("INSERT INTO clients(id,client_id,token_hash,enabled,rollback_available) VALUES(29,'fixture-client','synthetic-client-hash',1,1)")
db.execute("INSERT INTO self_service_sessions(id,username,expires_at,revoked_at) VALUES('fixture-session','Fixture','2030-01-02 03:04:05','2026-01-02 03:04:05')")
db.execute("INSERT INTO oidc_clients(client_id,secret_hash,redirect_uris,scopes) VALUES('fixture-app','synthetic-secret-hash','https://example.test/callback','openid')")
db.execute("INSERT INTO oidc_codes(code_hash,client_id,user_id,redirect_uri,scope,nonce,code_challenge,expires_at) VALUES('synthetic-code-hash','fixture-app',41,'https://example.test/callback','openid','synthetic-nonce','synthetic-challenge','2030-01-02 03:04:05')")

pgschema = schema.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
pgschema = pgschema.replace("DATETIME", "TIMESTAMPTZ").replace("COLLATE NOCASE", "")
pgschema = pgschema.replace("BOOLEAN NOT NULL DEFAULT 1", "BOOLEAN NOT NULL DEFAULT TRUE").replace("BOOLEAN NOT NULL DEFAULT 0", "BOOLEAN NOT NULL DEFAULT FALSE")
pgschema += "ALTER TABLE badges ADD COLUMN activation_pending BOOLEAN NOT NULL DEFAULT FALSE;"
pgschema += "CREATE UNIQUE INDEX idx_users_oidc_subject ON users(oidc_subject) WHERE oidc_subject<>'';"

statements = ["BEGIN;", "CREATE SCHEMA identity_synthetic_rehearsal;", "SET LOCAL search_path TO identity_synthetic_rehearsal;", pgschema]
tables = ("users", "badges", "audit_log", "clients", "self_service_sessions", "oidc_clients", "oidc_codes")
for table in tables:
    columns = list(db.execute(f"PRAGMA table_info({table})"))
    for row in db.execute(f"SELECT * FROM {table}"):
        values = []
        for column, value in zip(columns, row):
            if value is None:
                values.append("NULL")
            elif column[2] == "BOOLEAN":
                values.append("TRUE" if value else "FALSE")
            elif isinstance(value, int):
                values.append(str(value))
            else:
                text = str(value)
                if column[2] == "DATETIME":
                    text = datetime.datetime.fromisoformat(text).replace(tzinfo=datetime.timezone.utc).isoformat()
                values.append("'" + text.replace("'", "''") + "'")
        statements.append(f"INSERT INTO {table} ({','.join(c[1] for c in columns)}) VALUES ({','.join(values)});")
    if any(c[1] == "id" and c[2] == "INTEGER" for c in columns):
        statements.append(f"SELECT setval(pg_get_serial_sequence('{table}','id'),(SELECT max(id) FROM {table}));")
    statements.append(f"DO $$ BEGIN IF (SELECT count(*) FROM {table}) <> {db.execute(f'SELECT count(*) FROM {table}').fetchone()[0]} THEN RAISE EXCEPTION 'count mismatch'; END IF; END $$;")
statements.append("""DO $$ BEGIN
IF NOT EXISTS(SELECT 1 FROM users WHERE id=41 AND oidc_subject='stable-fixture-subject' AND pin_hash='synthetic-hash') THEN RAISE EXCEPTION 'subject/hash mismatch'; END IF;
IF NOT EXISTS(SELECT 1 FROM badges WHERE id=73 AND user_id=41 AND NOT enabled AND activation_pending AND token_hash='synthetic-token-hash') THEN RAISE EXCEPTION 'badge state mismatch'; END IF;
IF NOT EXISTS(SELECT 1 FROM audit_log WHERE id=19 AND success AND timestamp='2026-01-02T03:04:05Z'::timestamptz AND details='synthetic audit') THEN RAISE EXCEPTION 'audit mismatch'; END IF;
IF NOT EXISTS(SELECT 1 FROM clients WHERE id=29 AND enabled AND rollback_available AND token_hash='synthetic-client-hash' AND last_seen_at IS NULL) THEN RAISE EXCEPTION 'client mismatch'; END IF;
IF NOT EXISTS(SELECT 1 FROM self_service_sessions WHERE id='fixture-session' AND lower(username)='fixture' AND revoked_at IS NOT NULL) THEN RAISE EXCEPTION 'session mismatch'; END IF;
IF NOT EXISTS(SELECT 1 FROM oidc_clients WHERE client_id='fixture-app' AND enabled AND secret_hash='synthetic-secret-hash' AND redirect_uris='https://example.test/callback') THEN RAISE EXCEPTION 'client registration mismatch'; END IF;
END $$;
DO $$ BEGIN
BEGIN INSERT INTO badges(badge_code,user_id,token_hash) VALUES('BAD-FK',99999,'synthetic'); RAISE EXCEPTION 'foreign key not enforced'; EXCEPTION WHEN foreign_key_violation THEN NULL; END;
BEGIN INSERT INTO users(username,display_name,oidc_subject) VALUES('duplicate-subject','Duplicate','stable-fixture-subject'); RAISE EXCEPTION 'subject uniqueness not enforced'; EXCEPTION WHEN unique_violation THEN NULL; END;
END $$;
DO $$ DECLARE affected integer; BEGIN
UPDATE oidc_codes SET consumed_at=now() WHERE code_hash='synthetic-code-hash' AND consumed_at IS NULL AND expires_at>now(); GET DIAGNOSTICS affected=ROW_COUNT; IF affected<>1 THEN RAISE EXCEPTION 'code consumption failed'; END IF;
UPDATE oidc_codes SET consumed_at=now() WHERE code_hash='synthetic-code-hash' AND consumed_at IS NULL; GET DIAGNOSTICS affected=ROW_COUNT; IF affected<>0 THEN RAISE EXCEPTION 'code replay accepted'; END IF;
END $$;
INSERT INTO users(username,display_name) VALUES('sequence-fixture','Sequence');
DO $$ BEGIN IF (SELECT id FROM users WHERE username='sequence-fixture')<=41 THEN RAISE EXCEPTION 'sequence mismatch'; END IF; END $$;
ROLLBACK;""")
result = subprocess.run([psql_binary, "-X", "-q", "-v", "ON_ERROR_STOP=1", "-h", "127.0.0.1", "-p", "55441", "-U", "postgres", "-d", "postgres"], input="\n".join(statements), text=True, capture_output=True, timeout=30)
if result.returncode:
    raise RuntimeError(result.stderr)
psql = [psql_binary, "-X", "-q", "-v", "ON_ERROR_STOP=1", "-h", "127.0.0.1", "-p", "55441", "-U", "postgres", "-d", "postgres"]
failed = subprocess.run(psql, input="BEGIN; CREATE SCHEMA identity_failed_rehearsal; CREATE TABLE identity_failed_rehearsal.rows(id integer PRIMARY KEY); INSERT INTO identity_failed_rehearsal.rows VALUES(1),(1); COMMIT;", text=True, capture_output=True, timeout=30)
if failed.returncode == 0:
    raise RuntimeError("injected import failure did not fail")
checked = subprocess.run(psql, input="DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_namespace WHERE nspname IN ('identity_failed_rehearsal','identity_synthetic_rehearsal')) THEN RAISE EXCEPTION 'rehearsal residue'; END IF; END $$;", text=True, capture_output=True, timeout=30)
if checked.returncode:
    raise RuntimeError(checked.stderr)
print("All seven synthetic tables transferred; counts, IDs, hashes/subjects, timestamps, nulls, foreign keys, code replay and sequence checks passed; transaction rolled back.")
print("Injected duplicate-key import failure rolled back without schema residue.")
